### ISSUE TITLE
The MiSTer I/O board does not output the proper voltages on the DB15 connector to allow for automated AV features over SCART

### ISSUE THREAD

**Issue by mathieulh** [MiSTer-devel/Hardware_MiSTer#10]
The I/O board should be revised to add voltage to SCART PINs 8; 18 and 16
so it gets on spec and allows for automated AV selection

This would mean using unused pins on the DB15 connector for voltages and modifying the MiST cables.

This would allow automated AV features (assuming you switch to an updated MiST SCART cable) as per official SCART specifications

This way MiSTer could:
* Automatically turn on your TV
* Automatically switch your TV set to the AV channel on sets that support it (most sold in Europe since the mid 90s)
* Force force the use of specific signals over the same RGB cable (for instance switch from RGB to composite without changing the cable)
* Force 4:3 or Widescren aspects ratio (should someone ever need that)

More details regarding those specifications and features are available here: 

http://forum.arcadecontrols.com/index.php/topic,77370.msg806492.html#msg806492

and

http://forum.arcadecontrols.com/index.php/topic,77370.msg830465.html#msg830465

**Comment by sorgelig** [comment]
Sorry, it's out of MiSTer scope.
VGA connector has option "VGA_PWR through pin 9. It may output 3.3V or 5V. If you want other voltages, then you need to add external step-up DC-DC converter.
