### ISSUE TITLE
Request: STEP or STL files for each board for easier CAD design of accessories.

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/Hardware_MiSTer#15]
I would love if I could load a STEP or STL file of the boards and their components in one of the many free CAD programs out there to begin designing 3d printed cases and accessories. Unfortunately this currently requires extremely expensive premium software to even export these, and there are tools online like altium2kicad but they are not very functional. I realize that moving to open source PCB design tools is undesirable however can some of the paywall-locked features like STEP/STL export from the Altium format be at least provided for us here?

Thank you!

**Comment by KhalidHisham** [comment]
you mean like this? 
[sdram_xsd 3D-model.zip](https://github.com/MiSTer-devel/Hardware_MiSTer/files/6337187/sdram_xsd.3D-model.zip)

I am new to github so I am not sure how to upload the files to the repo otherwise I can help. 

\K

**Comment by birdybro** [comment]
That's perfect, yes! Thanks!

The workflow to contribute on GitHub is pretty easy to learn. I use GitHub Desktop.

1. Fork this repository on GitHub.
2. Clone it to your local storage in Github Desktop.
3. Put the Step files in the appropriate location (in this case `Hardware_MiSTer/Addons/SDRAM_xsd/sdram_xsd.step` would be appropriate).
4. Commit the changes in GitHub Desktop.
5. Push to your fork.
6. Submit a pull request.

https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop

**Comment by KhalidHisham** [comment]
Thanks, I will do it as soon as I can. 
Perhaps it will be cleaner to put all the step files in one folder?

**Comment by birdybro** [comment]
Maybe. I usually try to match the folder structure that the repository
already has to make it more agreeable to the maintainer of that repo.

**Comment by KhalidHisham** [comment]
Ok so I generated everything but it seems i can't add the files using GitHub desktop. for some reason no changes are shown when I simply put the files in their respective places. Is there a way to fix?

**Comment by birdybro** [comment]
Looks like it worked!

![image](https://user-images.githubusercontent.com/16388068/115561827-2aec4c80-a273-11eb-8a6a-eb5c6baf28c6.png)

Next you have to submit the pull request.

![image](https://user-images.githubusercontent.com/16388068/115561932-3fc8e000-a273-11eb-80e8-27bd20299765.png)

![image](https://user-images.githubusercontent.com/16388068/115562050-5c651800-a273-11eb-80ff-dd98afbbfde9.png)

![image](https://user-images.githubusercontent.com/16388068/115562174-7868b980-a273-11eb-85dd-a76987cb6a88.png)

:)

**Comment by KhalidHisham** [comment]
That was quite detailed, 
Thanks :)

**Comment by birdybro** [comment]
Glad to help. Welcome to GitHub! 👍🏻

**Comment by KhalidHisham** [comment]
Thank you. It is done now. 

I found out the problem I had with the gitHub desktop. It seems that the all STEP files are placed on ignore list in the repository configuration. So I decided to zip all the files before adding them to their respective folders and it worked.

**Comment by sorgelig** [comment]
it's on repo now
