### ISSUE TITLE
SDRAM XSDS v2.9 missing part number

### ISSUE THREAD

**Issue by prrole** [MiSTer-devel/Hardware_MiSTer#18]
There is no part number for P1 2x20 SMD connector in schematics or pcb file.  The 3D model shows a connector that is not common or easy to source, so a part number/source is needed to build this board.

**Comment by sorgelig** [comment]
Because it's common connector without specific part number.
you can find it on Aliexpress or eBay.
you may order this one:
http://www.townes.com.tw/product_detail/land-ctop-2/index.php?Product_SN=68153
