### ISSUE TITLE
SDRAM XSDS v2.9 has a strange solder pad.

### ISSUE THREAD

**Issue by type78** [MiSTer-devel/Hardware_MiSTer#20]
![IMG_20210628_231425](https://user-images.githubusercontent.com/11624457/124208024-b01c9900-db21-11eb-9dcc-2da9981b3846.jpg)

There's a strange small solder pad on v2.9 SDRAM PCB. (please see the picture I attached.)
Is it intended?  If it is, what's the purpse of this small pad?

**Comment by sorgelig** [comment]
it's an option. You may opt out LDO and solder that pad with nearby pin together to get 3.3V from de10-nano
