### ISSUE TITLE
Help with usb board

### ISSUE THREAD

**Issue by sonik-br** [MiSTer-devel/Hardware_MiSTer#22]
Hi,

My USB board is busted. The component over the U2a (NCP380LSNAJAAT1G) is burned and I can't find another to buy.
There's any equivalent component that will work?

![mister_usb](https://user-images.githubusercontent.com/16923826/147506502-23713a2f-4c4d-4e50-9cf9-0974ca4c6d77.jpg)

**Comment by sorgelig** [comment]
option 1: you may disable VBUS control, so you won't need this chip. USB devices will have permanent 5V supply from main power. Refer to schematics and notes there.
option 2: there are no equivalents. There is only version for uDFN6 case of the same chip which may hold slightly higher current than busted TSOP6 version.

**Comment by sonik-br** [comment]
Thanks for the answer.

I'm a layman in electronics .

What's the purpose of VBUS? If I get it right, it's to power on/off the usb hub in sync with mister's main board?

For option 1 I can just bridge the JP3? JP1 too?
It will drain power from the mister's usb or from external psu?

**Comment by sorgelig** [comment]
> What's the purpose of VBUS? If I get it right, it's to power on/off the usb hub in sync with mister's main board?

it allows USB host controller to turn power on/off of USB devices.

> For option 1 I can just bridge the JP3? JP1 too?

Short JP1. JP3 doesn't matter.

> It will drain power from the mister's usb or from external psu?

It will drain power from the same source as with VBUS control.

**Comment by sonik-br** [comment]
My board is dead. Even without VBUS. Power works but no data.
I've got a new one :)
