### ISSUE TITLE
MT32Pi Top Gerbers broken

### ISSUE THREAD

**Issue by Shadowtrance** [MiSTer-devel/Hardware_MiSTer#28]
Title.
It seems the gerbers for the MT32Pi Top piece are broken in some way.
When imported to jlcpcb this is the result (1).
And if you select the top or bottom after initial loading (2) you only see a corner of the pcb with a hole that isn't drilled out and not much else (3).
The main base board that actually matters _appears_ to be fine though _i think_.

1. ![Screenshot 2023-08-02 135129](https://github.com/MiSTer-devel/Hardware_MiSTer/assets/1887665/f01b2c36-1096-4873-ba97-c267d9f8300f)

2. ![Screenshot 2023-08-02 135519](https://github.com/MiSTer-devel/Hardware_MiSTer/assets/1887665/7861786a-7db7-4614-88a5-2606ac0b8c41)

3. ![Screenshot 2023-08-02 135746](https://github.com/MiSTer-devel/Hardware_MiSTer/assets/1887665/1eb3dd78-ba09-404b-808a-e0133a2a9231)

**Comment by sorgelig** [comment]
Their online gerber viewer is very buggy. Don't verify correctness there.

**Comment by Shadowtrance** [comment]
Well it wasn't just jlcpcb. I checked it in kicad gerber viewer and some others online all with slightly different but weird results.
I thought I was going a little crazy... hopefully not. haha Main appears to be fine on JLC in 2d and 3d views, but then different in kicad gerber viewer. So I don't know what to believe...

Top ![Screenshot 2023-08-02 183405](https://github.com/MiSTer-devel/Hardware_MiSTer/assets/1887665/a7c9cbd0-99e7-468f-9d02-82ca8171eb42)

Main ![Screenshot 2023-08-02 183451](https://github.com/MiSTer-devel/Hardware_MiSTer/assets/1887665/058e9f53-91c4-478a-872a-b79d99ae8dc7)

**Comment by sorgelig** [comment]
It's relative/absolute coordinate mistreat between drill and gerber. Don't worry. JLCPCB stuff will correct it. All boards i release I've ordered from JLCPCB already.

**Comment by Shadowtrance** [comment]
Ok yeah i have no idea what weirdness was happening with every gerber preview i looked at but i ordered them anyway and they can in today perfectly fine and not some weird cutout like the jlc preview showed for the top.
All good and thanks for creating the addons! :)
