### ISSUE TITLE
fix suggestion: remove possibility of wrong pin insert alignment

### ISSUE THREAD

**Issue by goofyseeker311** [MiSTer-devel/Hardware_MiSTer#30]
if there would be a socket, that would fit with the de10-nano in only one way,
or that there would be a protection circuit in case of wrong pins, there would be
no way to brick any of the boards. just saying as feedback as an user.
if you can break it, you will break it, like with the sdram board pin misalignment, into wrong pins.

**Comment by sorgelig** [comment]
If de10-nano would use shrouded connector like IDE HDD, then it would exclude wrong insertion. But DE10-nano uses naked pin header, so there is no way to prevent it. Adding protection circuit is impossible too.

When you buy a TV or phone, you buy it fully assembled. So do it with MiSTer too. Leave DIY option to professional people.

**Comment by goofyseeker311** [comment]
I'm a professional electrical engineer, and of course all is possible. there is a way to make a suitable socket.
but you do you. do you mean this device is only for the pros. very narrow focus. seems like linux.

hardware and software user interface and user experience, for all levels, being simple enough and reliable, matters.

as a sold product the quality assurance should be better than just "for pros only" statement.
you know they have brought companies to court because of hot coffee cup usage issues.

**Comment by sorgelig** [comment]
I don't sell anything, don't you know? I don't even get any revenue from sales besides some sellers donate sometimes to me.
This is hobby and community project.
Generally speaking it's supposed that you buy all components and solder all addon boards yourself bearing all risks on yourself.
If you buy a Raspberry Pi or Arduino boards and then randomly connect the pins, then any damage you made by that is not covered by board manufacturer. Same with MiSTer. 

As a community/hobby project it's developing with help from people wanting to share their improvements. Since you are professional (as you said), you may offer protection circuit or other improvements preventing wrong insertion.

**Comment by goofyseeker311** [comment]
just bringing up potential fixes/improvements, if someone wants to incorporate them. no forcing anyone.

the commercial selling issue is down the distribution line that will use the base model from this project.
better do the best right from the beginning, up-stream for the down-stream, right? that way everyone benefits.

****** improvement list ******
series resistances on the gpio data lines as usual to prevent any vcc short/high currents.
current diodes to prevent wrong way inserted current flow.
a bit wider io board sdram gap to fit an insertion prevention sleeve, even when without io board installed.
****** improvement list ******

yes my issue was possible when there was/is no io board to slot the sdram module. and my error was an accident.

by local law, in a commercial system it may not be up to you what you have to replace or fix.
for example in europe you have buyers return of a product and some quality control restrictions, even if you dont want to.
so even if you are not personally tied by law, then the sellers will be. they have to take account the law. you cant override the law.
ie terms of service, or end user license agreement is void against the general law requirements.

well at least when you would take the parts and solder the parts, you get what you make and do yourself.
even then you can burn a design that is burnable. best to do the best design right from the start.

talking to myself, taking account of the end user possible issues as soon as possible is ideal. of any type.
I talk here as hobbyist and professional computer/electronics system builder.

**Comment by sorgelig** [comment]
It's easy to suggest and it costs nothing. Just make a prototype which suits everything you've said. Spend the time, money, nerves and so on. 
Then come here to share everything here for free. 
Agree?

**Comment by goofyseeker311** [comment]
only half, its better to first state what the improvement is, so that anyone can do it, even if I would not be doing it.
then even I can do it, better have a good plan first, half the work, agree? then the idea of improvement can be evaluated.
first. this is the minimal effort required route. for everyone, including me. its ideal when it actually costs nothing.
nothing forced here. only if someone wants to. you or me, or none. for free.

I already put the core of the improvements as a list in one of the replies on this post.

also the sketch/core of the idea, before an actual implementation in design/hardware, is only provided here.

**Comment by goofyseeker311** [comment]
about the being a "pro", I do hold an uni master/semi-phd in electronics/semiconductor/nano-tech.

**Comment by sorgelig** [comment]
Theory is one thing, while practice can kill whatever you planned in the beginning. That's why i've said: make it and FULLY test.
I'm not going to implement your theories. It's YOU have to do it. You have to spend the time and everything required for that.
Put diodes, resistors or whatever, usually just to see it making SDRAM non-working, add workarounds, make hundred revisions of board, etc...
I've seen so many suggesting people. 90% of them just blah blah without anything real. 10% grab my design, rework it and never share back.

**Comment by goofyseeker311** [comment]
I dont like to be forced either.

this is how it works in the corporate world, where I would be a lead designer, not the implementer.
mostly being on the design requirements side of product process. but I could/can do it myself when I want to.

**Comment by sorgelig** [comment]
And there is 5V pin on connector, and whatever signal it collided on wrong insertion, it will damage the board because SDRAM is 3.3V. Go to protect it ;)

**Comment by goofyseeker311** [comment]
yes that 5V vs 3.3V is an issue, but it can be dealt with.

**Comment by sorgelig** [comment]
> I would be a lead designer, not the implementer.

I see, lol :)
So many suggesters and no implementers :)

**Comment by goofyseeker311** [comment]
I say this before even looking at the circuit design.
so how about the series resistor on all the data lines.
or maybe just a voltage divider from 5v to 3.3v.
and enough large resistor pair that no in-rush current can form.
any data line will not need a large current anyways.

**Comment by sorgelig** [comment]
> so how about the series resistor on all the data lines.

No problem. You can try it and report it here. You will need to design the board which will be able to fit ~30 resistors.

> or maybe just a voltage divider from 5v to 3.3v.

already added in recent SDRAM revisions. It has nothing to do with protection. Shifted insertion will put 5V on nearby signal.

**Comment by goofyseeker311** [comment]
it has all to do with the data line protection, input resistive voltage divider on the data lines of the ram chip, to prevent excessive current and voltage. its about mass current at 5v to actually burn stuff on wrong pin, not the 5v signal alone. it would not work with the 5v signal would it would not burn. I had the vcc connected to the data line. that burned it. or a short because of the wrong pins. I think there was 2A or whatever going through the short. through the SDRAM board. near/through some chip. or it burned some thin wires with the heat. resistors can be super small, non-issue. SMD super small resistors. and the board can be made a bit taller possibly to fit the resistors. or just move the "this side faces outward" text to the socket and use that space. maybe there is even a resistor matrix-on-a-chip type of solution. or just a plain memory chip protection circuit off-the-shelf. I wonder why there would not be a chip internal high current/voltage protection circuit integrated, tho, in the sdram chips.

the easiest solution could be just that simple, to use a protected sdram chip/s instead of the unprotected chips.

those pins should be already high impedance, so I think the burning is related to some other circuit mess-up happening with the pins. meh 40ohms or so at 5V equals 125mA of current. 100mA can burn a led/diode. and a transistor. 100mA through multiple data lines at once say 2A on combined 20 lines close-by and inside integrated chip would heat up a chip and burn it.

**Comment by goofyseeker311** [comment]
yeah I would just put a resistive voltage divider on the data lines, even if it has high output impedance not matching the sdram chip data lines impedance. in other words I would increase the impedance of the chip data lines, in some way, integrated internally or externally by resistor voltage divider buffer stage.

come on micron, dont just put low resistive impedance pins on your chips for no reason. not for "low impedance" connections sake either. no signal needs high current. high impedance it is.

the whole chip protection issue is even subject to recent research:
https://ietresearch.onlinelibrary.wiley.com/doi/full/10.1049/el.2017.3634

memory controller ODT of 240ohms is much better. maybe use a separate memory controller on the SDRAM board. which has all the current/voltage protections implemented. all this because some connections can be inserted in wrong pins. there might be an additional benefit of using a memory controller instead of direct FPGA usage of the SDRAM chips. less gpio pins needed per chip etc.

**Comment by goofyseeker311** [comment]
meh simplest would be just make sure the io board and sdram pins will not go into wrong holes even by force.
prevention socket extension shroud on the sdram and the io board. you know those motherboard connectors. but just extra blocked holes in this mister case. or just widenedd socket walls so it will not fit in any other way than the designed way.

I can draw the socket sleeve extenders if you want to.

**Comment by sorgelig** [comment]
couple more hours and you will say that current board design is fine.
Laziness is the strongest force!

**Comment by goofyseeker311** [comment]
lol :) I wont say that tho. I like the best, with minimal effort, with no compromise.
lazyness means some critical compromise is let through, without thinking it through.
I mean the difference between a good prototype for testing vs polished end result.

even if all stays as it is, and its fine enough, there will be burned memory modules.
even for pros. think about tinkerers fixing their own boards. burns. as usual.

what for are the two plates that come with the io board, with the holes. for the cases?
those case plates could be an add-on safe-guard sleeves for the connectors.

self-note: assume that none will read any instructions or use any pieces properly.
edit: assume none will get the instructions correctly even if they have read it, fully or partially.
edit: even if there is documentation, there will be stuff missing from the documentation.

therefore everything should be self-sufficient.

**Comment by goofyseeker311** [comment]
this is fine. lol. said the one who's house burned down. because of the house being built out of wood.

for the SDRAM. top version is the current SDRAM socket. bottom version is the extra sleeve socket.
you get what I'm after here. yep its a non-standard larger socket.
the sleeve blocks inserting the SDRAM socket connector in wrong pins.
but it still allows the SDRAM module to be inserted inverted, like its in the sockit mister expansion board.
might require more room in the top io board, if you want to remove/insert memory module without removing the io board.
also if the connector is larger, then it will punch out of the case, if the case is exactly the same size as the de10nano board.
![sockets2](https://github.com/MiSTer-devel/Hardware_MiSTer/assets/19920254/29b46097-d9ed-4c31-a307-62c1490cce03)

ps. actually in the sockit mister there is the IDE connector slot on the other side of the gpio expansion connector.
and yep I do have both the de10nano mister and sockit mister working. physically.

exactly same idea for the io-board or any other "be sure" type of expansion. possibly the extra guard sleeves are on by default, but could be removed, from the connector sockets. if I "work" on this subject any more, then it goes to tinkering territory.

ps. the sdram memory module does not burn inverted in the gpio socket, tested that on the arrow sockit. having the pins mis-aligned will burn the sdram chip. and I burned one of my chips with the sockit mister, with mis-aligned pins.

my thesis: do stuff free smarter, dont work harder.

**Comment by goofyseeker311** [comment]
if you like safety wheel guard in mister. but if you dont tell them, that its a safety wheel system. lol.
feature by default, not a bug.
