### ISSUE TITLE
Q: Is it possible to use only one bank of the SDRAM XSD v2.5

### ISSUE THREAD

**Issue by waagbo** [MiSTer-devel/Hardware_MiSTer#7]
Hi,
Thanks to everyone for designing and creating this well documented DYI-system.

I just realized the relatively high prices of the 512M Alliance Memory SD modules.
Is it possible to mount only one chip in the dual PCB and add the second memory chip at a later time?

**Comment by sorgelig** [comment]
You can try. It may have slightly different timings and some cores may misbehave.
I have such module, it works ok together with recently updated cores.
